<a href="https://colab.research.google.com/github/LaputMarkDanielle/CPE-201L-DSA-2-A/blob/main/Midterm-TestSkill.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

def main():
    arr = np.arange(20, 50, 2)
    print("  EVEN INTEGERS:")
    display(arr)

    while True:
        print("\nMenu:")
        print("A. Display elements")
        print("B. Find the maximum element")
        print("C. Reverse the array")
        print("Type Exit to End")
        choice = input("Enter your choice (a,b,c): ")

        if choice == 'a':
            print("Elements of the array:")
            display(arr)
        elif choice == 'b':
            max_element = np.max(arr)
            print("\nMaximum element:")
            display(max_element)
        elif choice == 'c':
            reversed_array = np.flip(arr)
            print("\nReversed array:")
            display(reversed_array)
        elif choice == 'exit':
            print("ByeBye.")
            break
        else:
            print("Invalid choice. Please enter a number between A,B and C.")

if __name__ == "__main__":
    main()

  EVEN INTEGERS:


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])


Menu:
A. Display elements
B. Find the maximum element
C. Reverse the array
Type Exit to End
Enter your choice (a,b,c): a
Elements of the array:


array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])


Menu:
A. Display elements
B. Find the maximum element
C. Reverse the array
Type Exit to End
Enter your choice (a,b,c): b

Maximum element:


np.int64(48)


Menu:
A. Display elements
B. Find the maximum element
C. Reverse the array
Type Exit to End
Enter your choice (a,b,c): c

Reversed array:


array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20])


Menu:
A. Display elements
B. Find the maximum element
C. Reverse the array
Type Exit to End
Enter your choice (a,b,c): exit
ByeBye.
